# Generated by Django 5.2.1 on 2025-06-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bin_id", models.CharField(max_length=50, unique=True)),
                ("fill_level", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("organic_percentage", models.FloatField()),
                ("plastic_percentage", models.FloatField()),
                ("metal_percentage", models.FloatField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
