# Generated by Django 5.2.1 on 2025-06-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DumpingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spot_id", models.CharField(max_length=50, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "total_capacity",
                    models.FloatField(
                        help_text="Total capacity in arbitrary units, e.g., volume or weight"
                    ),
                ),
                (
                    "organic_content",
                    models.FloatField(
                        default=0.0, help_text="Current organic waste content"
                    ),
                ),
                (
                    "plastic_content",
                    models.FloatField(
                        default=0.0, help_text="Current plastic waste content"
                    ),
                ),
                (
                    "metal_content",
                    models.FloatField(
                        default=0.0, help_text="Current metal waste content"
                    ),
                ),
            ],
        ),
    ]
