# Generated by Django 5.2.3 on 2025-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='longitude',
        ),
        migrations.AddField(
            model_name='truck',
            name='assigned_route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='fuel_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('IDLE', 'Idle'), ('MAINTENANCE', 'Maintenance')], max_length=20, null=True),
        ),
    ]
