# Generated by Django 5.2.3 on 2025-06-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_truck_latitude_remove_truck_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='assigned_route',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='speed',
        ),
        migrations.AlterField(
            model_name='truck',
            name='current_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='truck',
            name='current_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fuel_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IDLE', 'Idle'), ('MAINTENANCE', 'Maintenance')], default='IDLE', max_length=20),
        ),
    ]
