# Generated by Django 5.2.3 on 2025-08-24 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='bin_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Bin ID must contain only uppercase letters, numbers, hyphens, and underscores.', regex='^[A-Z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='bin',
            name='fill_level',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Fill level cannot be negative'), django.core.validators.MaxValueValidator(100.0, message='Fill level cannot exceed 100%')]),
        ),
        migrations.AlterField(
            model_name='bin',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0, message='Latitude must be between -90 and 90'), django.core.validators.MaxValueValidator(90.0, message='Latitude must be between -90 and 90')]),
        ),
        migrations.AlterField(
            model_name='bin',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0, message='Longitude must be between -180 and 180'), django.core.validators.MaxValueValidator(180.0, message='Longitude must be between -180 and 180')]),
        ),
        migrations.AlterField(
            model_name='bin',
            name='metal_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Metal percentage cannot be negative'), django.core.validators.MaxValueValidator(100.0, message='Metal percentage cannot exceed 100%')]),
        ),
        migrations.AlterField(
            model_name='bin',
            name='organic_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Organic percentage cannot be negative'), django.core.validators.MaxValueValidator(100.0, message='Organic percentage cannot exceed 100%')]),
        ),
        migrations.AlterField(
            model_name='bin',
            name='plastic_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Plastic percentage cannot be negative'), django.core.validators.MaxValueValidator(100.0, message='Plastic percentage cannot exceed 100%')]),
        ),
    ]
