# Generated by Django 5.2.5 on 2025-09-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_id',
            field=models.CharField(help_text='Unique identifier for the sensor device', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='sensordata',
            unique_together={('sensor_id', 'timestamp')},
        ),
    ]
