# Generated by Django 5.2.5 on 2025-09-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sensordata_sensor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('camera_type', models.CharField(choices=[('ESP32_CAM', 'ESP32-CAM'), ('USB', 'USB Camera'), ('IP', 'IP Camera'), ('RASPBERRY_PI', 'Raspberry Pi Camera')], default='ESP32_CAM', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('OFFLINE', 'Offline'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('rtsp_url', models.URLField(blank=True, null=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CameraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camera_images/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='camera_thumbnails/%Y/%m/%d/')),
                ('analysis_type', models.CharField(choices=[('WASTE_CLASSIFICATION', 'Waste Classification'), ('SECURITY', 'Security Monitoring'), ('COLLECTION', 'Collection Verification'), ('GENERAL', 'General Monitoring')], default='GENERAL', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('detected_objects', models.JSONField(blank=True, default=dict)),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.camera')),
            ],
            options={
                'verbose_name': 'Camera Image',
                'verbose_name_plural': 'Camera Images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['camera', 'created_at'], name='core_camera_camera__7d14d9_idx'), models.Index(fields=['analysis_type', 'created_at'], name='core_camera_analysi_a1cb5a_idx'), models.Index(fields=['is_analyzed', 'created_at'], name='core_camera_is_anal_96dd5c_idx')],
            },
        ),
    ]
